version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ferrega_db
    env_file:
      - db/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: ferrega_backend
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - app/.env
    volumes:
      - ./app:/app
      - ./app/data:/app/app/data
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    container_name: ferrega_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: